print("Getting to Know you better!")
print()
userName = input("What's your name? ")
print("Your name is" )
print(userName)
urFood = input("what's your favorite food? ")
print("Your favourite food is ")
print(urFood)
urMusic = input("What's is your favorite music? ")
print("Your favorite music is ")
print(urMusic)
urState = input("Where do you live? ")
print("You live at ")
print(urState)
print("Thanks for the information!")
