print("=== The Ultimate Wacky Recipe Maker===")
print()
Food = input("Name of Food: " )
Plant = input("Name of Plant: " )
Cooking = input("Method of cooking: " )
Burned = input("A word to describe burned food: " )
Item = input("A household item: ")
print()
print("Tonight's dinner:")
print()
print("For dinner you should make", Cooking, Food, "with", Burned, Plant, "on a plate of", Item )
